#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  startButton,    sensorTouch)
#pragma config(Sensor, dgtl11, sonar1,         sensorSONAR_inch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           motor2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           emotor1,       tmotorVex269_MC29, openLoop, reversed, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int sonarCheck = 0;
bool turn1Done = false;
bool turn2Done = false;

task main()
{
getMotorEncoder(emotor1);


bool buttonStop = false;
  while(1==1)
{
	//start the robot forward upon the button press
	 if (SensorValue(startButton) == 1 && buttonStop == false)
	{
		resetMotorEncoder(emotor1);
		startMotor(motor1, 40);
		startMotor(motor2, 40);
	}
		//scan the environment to see if 1st barrier is observed
		if (SensorValue(sonar1) <= 50 && SensorValue(sonar1) >= 5 && turn1Done == false)
		{
			
			//wall detected
			sonarCheck++;
			waitInMilliseconds(20);

			if (sonarCheck >= 35)
			{
				//initiate 1st left turn
				//start tracking motor encoder during turn
				while(getMotorEncoder(emotor1) <= 450 && turn1Done == false)
					{
						startMotor(emotor1, 95);
						
					}
					//turn 1 is complete
					stopMotor(emotor1);
					resetMotorEncoder(emotor1);
					sonarCheck = 0;
					turn1Done = true;
					wait(.5);
			}
		
		}
		
		//scan the environment to see if 2nd barrier is observed
		if (SensorValue(sonar1) <= 40 && SensorValue(sonar1) >= 1 && turn1Done == true && turn2Done == false)
		{
			sonarCheck++;
			waitInMilliseconds(20);
			
			if (sonarCheck >= 35)
			{
				//start motor encoder for right turn
				while(abs(getMotorEncoder(emotor1)) <= 450)
					{
						startMotor(emotor1, -95);
						
					}
					//turn 2 is complete, stop motor
					stopMotor(emotor1);
					resetMotorEncoder(emotor1);
					sonarCheck = 0;
					turn2Done = true;
				}
			}
	}
}
