#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  startButton,    sensorTouch)
#pragma config(Sensor, dgtl11, sonar1,         sensorSONAR_inch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           motor2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           emotor1,       tmotorVex269_MC29, openLoop, reversed, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
getMotorEncoder(emotor1);

bool buttonStop = false;
  while(1==1)
{
//untilBump(startButton, 0);
 if (SensorValue(startButton) == 1 && buttonStop == false)
{
resetMotorEncoder(emotor1);
startMotor(motor1, 80);
startMotor(motor2, 80);


while(getMotorEncoder(emotor1) < 1700)
{
startMotor(emotor1, 127);
}
stopMotor(emotor1);


buttonStop = true;
wait(1);
}

if (SensorValue(startButton) == 1 && buttonStop == true)
{
wait(1);
stopMotor(motor1);
stopMotor(motor2);
stopMotor(emotor1);

buttonStop = false;
}
}

}
