#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  startButton,    sensorTouch)
#pragma config(Sensor, dgtl11, sonar1,         sensorSONAR_inch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           motor2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           emotor1,       tmotorVex269_MC29, openLoop, reversed, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
resetMotorEncoder(emotor1);
getMotorEncoder(emotor1);
int sonarCheck = 0;
bool turn1Done = false;


bool buttonStop = false;
  while(1==1)
{
	//start the robot forward upon the button press
	 if (SensorValue(startButton) == 1 && buttonStop == false)
	{
		resetMotorEncoder(emotor1);
		startMotor(motor1, 40);
		startMotor(motor2, 40);
	}

		if (SensorValue(sonar1) <= 50 && SensorValue(sonar1) >= 5)
		{

			sonarCheck++;
			waitInMilliseconds(20);

			if (sonarCheck >= 35)
			{
						//stop encoder motor when 1960 rotations occur
				while(getMotorEncoder(emotor1) <= 450 && turn1Done == false)
					{
						startMotor(emotor1, 95);
						sonarCheck = 0;
					}

					stopMotor(emotor1);
					turn1Done = true;
			}
		}
		resetMotorEncoder(emotor1);
		//2nd turn
if (SensorValue(sonar1) <= 15 && SensorValue(sonar1) >= 1)
		{

			sonarCheck++;
			waitInMilliseconds(20);

			if (sonarCheck >= 35)
			{
						//stop encoder motor
				while(getMotorEncoder(emotor1) <= -450)
					{
						startMotor(emotor1, -95);
						sonarCheck = 0;
					}

					stopMotor(emotor1);
				}
			}
	}
}
